version: "3"
services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    tty: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ports:
      - "9090:9090"
    volumes:
      - "prometheus_data:/prometheus"
      - "./Configs/Prometheus/Prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./Configs/Prometheus/Rules.yml:/etc/Rules.yml"
      - "./ServiceDiscovery:/etc/prometheus/ServiceDiscovery"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'
  alertmanager:
    image: prom/alertmanager:main
    container_name: alertmanager
    depends_on:
      - prometheus
    tty: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ports:
      - "9093:9093"
    volumes:
      - "alertmanager_data:/data"
      - "./Configs/Alertmanager/Config.yml:/alertmanager/alertmanager.yml"
      - "./Configs/Alertmanager/Notifications.tmpl:/alertmanager/Notification.tmpl"
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
      - '--cluster.advertise-address=0.0.0.0:9093'
      - '--storage.path=/data'
      - '--log.level=debug'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    restart: unless-stopped
    depends_on:
      - prometheus 
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./Configs/Grafana/DataSources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./Configs/Grafana/Dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "./Configs/Grafana/GeneralStatusDashboard.yml:/etc/grafana/provisioning/dashboards/general-status-dashboard.json"
      - "./Configs/Grafana/NodeExporterDashboard.yml:/etc/grafana/provisioning/dashboards/node-exporter-full-dashboard.json"
volumes:
  grafana_data: {}
  prometheus_data: {}
  alertmanager_data: {}
